[alembic]

# path to migration scripts
dir = alembic

# template used to generate migration files
# file_template = %%(rev)s_%%(slug)s

# path to .env file
env_file = .env

# logging level
display_sql = False
log_level = INFO