name: Pull Request

on:
  pull_request:

permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: read

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    secrets: inherit
